openapi: 3.0.1
info:
  description: Description of the DLB API
  title: Dedicated Load Balancer API
  version: 1.0.0
servers:
- description: Anypoint Cloudhub
  url: https://anypoint.mulesoft.com/cloudhub/api/
- description: Anypoint Cloudhub EU
  url: https://eu1.anypoint.mulesoft.com/cloudhub/api/
- description: Anypoint Cloudhub GOV
  url: https://gov.anypoint.mulesoft.com/cloudhub/api/
security:
- bearerAuth: []
paths:
  /organizations/{orgId}/vpcs/{vpcId}/loadbalancers:
    get:
      description: Returns all loadbalancers in the given vpc
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the VPC in GUID format
        explode: false
        in: path
        name: vpcId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_organizations__orgId__vpcs__vpcId__loadbalancers_get_200_response'
          description: Success response
    post:
      description: create a DLB
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the VPC in GUID format
        explode: false
        in: path
        name: vpcId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlbPostBody'
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_organizations__orgId__vpcs__vpcId__loadbalancers_post_400_response'
          description: Bad request response
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlb'
          description: Success response
  /organizations/{orgId}/vpcs/{vpcId}/loadbalancers/{dlbId}:
    delete:
      description: Deletes a DLB
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the VPC in GUID format
        explode: false
        in: path
        name: vpcId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the DLB in GUID format
        explode: false
        in: path
        name: dlbId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          description: Success response
    get:
      description: Retrieves a DLB by id
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the VPC in GUID format
        explode: false
        in: path
        name: vpcId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the DLB in GUID format
        explode: false
        in: path
        name: dlbId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlb'
          description: Success response
    patch:
      description: Updates a dlb. uses JSON Patch body object
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the VPC in GUID format
        explode: false
        in: path
        name: vpcId
        required: true
        schema:
          type: string
        style: simple
      - description: The ID of the DLB in GUID format
        explode: false
        in: path
        name: dlbId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jsonPatch'
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_organizations__orgId__vpcs__vpcId__loadbalancers_post_400_response'
          description: Bad request response
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlb'
          description: Success response
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_organizations__orgId__vpcs__vpcId__loadbalancers_post_400_response'
      description: Bad request response
    SuccessGetDLB:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/dlb'
      description: Success response
    SuccessPostDLB:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/dlb'
      description: Success response
    SuccessPutDLB:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/dlb'
      description: Success response
    SuccessDeleteDLB:
      description: Success response
    SuccessListDLBs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_organizations__orgId__vpcs__vpcId__loadbalancers_get_200_response'
      description: Success response
  schemas:
    dlb:
      allOf:
      - $ref: '#/components/schemas/dlbExtras'
      - $ref: '#/components/schemas/dlbCore'
      title: dlb
    dlbCore:
      properties:
        name:
          example: myAwesomeDLB
          title: name
          type: string
        state:
          default: STOPPED
          description: dlb state
          title: state
          type: string
        ipWhitelist:
          items:
            type: string
          title: ipWhitelist
          type: array
        ipAllowlist:
          items:
            type: string
          title: ipAllowlist
          type: array
        httpMode:
          default: redirect
          title: httpMode
          type: string
        defaultSslEndpoint:
          default: 0
          example: 0
          title: defaultSslEndpoint
          type: integer
        tlsv1:
          example: false
          title: tlsv1
          type: boolean
        sslEndpoints:
          items:
            $ref: '#/components/schemas/dlbCore_sslEndpoints_inner'
          type: array
      title: dlbCore
      type: object
    dlbExtras:
      properties:
        id:
          description: The dlb Id
          example: 619d1c270322c72f81663c12
          title: id
          type: string
        domain:
          description: dlb domain
          title: domain
          type: string
        deploymentId:
          description: the dlb deployment id
          title: deploymentId
          type: string
        instanceConfig:
          $ref: '#/components/schemas/instanceConfig'
        ipAddresses:
          items:
            type: string
          title: ipAddresses
          type: array
        staticIPsDisabled:
          title: staticIPsDisabled
          type: boolean
        vpcId:
          title: vpcId
          type: string
        workers:
          title: workers
          type: integer
        defaultCipherSuite:
          title: defaultCipherSuite
          type: string
        keepUrlEncoding:
          title: keepUrlEncoding
          type: boolean
        upstreamTlsv12:
          title: upstreamTlsv12
          type: boolean
        proxyReadTimeout:
          title: proxyReadTimeout
          type: integer
        ipAddressesInfo:
          items:
            $ref: '#/components/schemas/dlbExtras_ipAddressesInfo_inner'
          type: array
        doubleStaticIps:
          title: doubleStaticIps
          type: boolean
        enableStreaming:
          title: enableStreaming
          type: boolean
        forwardClientCertificate:
          title: forwardClientCertificate
          type: boolean
      title: dlbExtras
      type: object
    jsonPatch:
      items:
        $ref: '#/components/schemas/updateObject'
      title: jsonPatch
      type: array
    dlbPostBody:
      properties:
        name:
          example: myAwesomeDLB
          title: name
          type: string
        state:
          default: STOPPED
          description: dlb state
          title: state
          type: string
        domain:
          description: The DNS domain for the Load Balancer
          title: domain
          type: string
        ipWhitelist:
          items:
            type: string
          title: ipWhitelist
          type: array
        ipAllowlist:
          items:
            type: string
          title: ipAllowlist
          type: array
        httpMode:
          default: redirect
          title: httpMode
          type: string
        defaultSslEndpoint:
          default: 0
          example: 0
          title: defaultSslEndpoint
          type: integer
        tlsv1:
          example: false
          title: tlsv1
          type: boolean
        keepUrlEncoding:
          example: false
          title: keepUrlEncoding
          type: boolean
        upstreamTlsv12:
          example: false
          title: upstreamTlsv12
          type: boolean
        staticIPsDisabled:
          title: staticIPsDisabled
          type: boolean
        doubleStaticIps:
          title: doubleStaticIps
          type: boolean
        enableStreaming:
          title: enableStreaming
          type: boolean
        forwardClientCertificate:
          title: forwardClientCertificate
          type: boolean
        workers:
          default: 2
          description: the dedicated load balancer's number of workers.
          enum:
          - 2
          - 4
          - 6
          - 8
          maximum: 8
          minimum: 2
          title: workers
          type: integer
        proxyReadTimeout:
          default: "300"
          description: Sets the Mule application response timeout value.
          title: proxyReadTimeout
          type: string
        sslEndpoints:
          items:
            $ref: '#/components/schemas/dlbPostBody_sslEndpoints_inner'
          type: array
      title: dlbPostBody
      type: object
    _organizations__orgId__vpcs__vpcId__loadbalancers_get_200_response:
      example:
        total: 0
        data:
        - null
        - null
      properties:
        data:
          items:
            $ref: '#/components/schemas/dlb'
          title: List of DLBs
          type: array
        total:
          title: Total number of results
          type: integer
      type: object
    _organizations__orgId__vpcs__vpcId__loadbalancers_post_400_response:
      properties:
        status:
          default: 400
          title: the response status code
          type: integer
        message:
          example: A sample message here
          title: the error message
          type: string
      type: object
    dlbCore_sslEndpoints_inner_mappings_inner:
      properties:
        inputUri:
          example: "{app}/"
          title: inputUri
          type: string
        appName:
          example: "{app}"
          title: appName
          type: string
        appUri:
          example: /
          title: appUri
          type: string
        upstreamProtocol:
          example: http
          title: upstreamProtocol
          type: string
      type: object
    dlbCore_sslEndpoints_inner:
      properties:
        privateKeyLabel:
          title: privateKeyLabel
          type: string
        privateKeyDigest:
          title: privateKeyDigest
          type: string
        publicKeyLabel:
          title: publicKeyLabel
          type: string
        publicKeyDigest:
          title: publicKeyDigest
          type: string
        publicKeyCN:
          title: publicKeyCN
          type: string
        clientCertLabel:
          title: clientCertLabel
          type: string
        clientCertDigest:
          title: clientCertDigest
          type: string
        clientCertCN:
          title: clientCertCN
          type: string
        revocationListLabel:
          title: revocationListLabel
          type: string
        revocationListDigest:
          title: revocationListDigest
          type: string
        verifyClientMode:
          default: "off"
          title: verifyClientMode
          type: string
        mappings:
          items:
            $ref: '#/components/schemas/dlbCore_sslEndpoints_inner_mappings_inner'
          type: array
      type: object
    instanceConfig:
      properties:
        imageName:
          title: imageName
          type: string
      title: instanceConfig
      type: object
    dlbExtras_ipAddressesInfo_inner:
      properties:
        ip:
          title: ip
          type: string
        status:
          title: status
          type: string
        staticIp:
          title: staticIp
          type: boolean
      type: object
    updateObject:
      properties:
        op:
          enum:
          - replace
          - add
          - remove
          title: op
          type: string
        path:
          example: /state
          title: path
          type: string
        value:
          title: value
      title: updateObject
      type: object
    dlbPostBody_sslEndpoints_inner_mappings_inner:
      properties:
        inputUri:
          example: "{app}/"
          title: inputUri
          type: string
        appName:
          example: "{app}"
          title: appName
          type: string
        appUri:
          example: /
          title: appUri
          type: string
        upstreamProtocol:
          default: http
          enum:
          - http
          - https
          - ws
          - wss
          example: https
          title: upstreamProtocol
          type: string
      type: object
    dlbPostBody_sslEndpoints_inner:
      properties:
        privateKeyLabel:
          title: privateKeyLabel
          type: string
        privateKey:
          example: |
            -----BEGIN PRIVATE KEY-----
            MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQ
            -----END PRIVATE KEY-----
          title: privateKey
          type: string
        publicKeyLabel:
          title: publicKeyLabel
          type: string
        publicKey:
          example: |
            -----BEGIN CERTIFICATE-----
            MIIDMjCCAhoCCQCju+T7DvAhIzANBgkqhkiG9w0BAQsFADBbMQs
            -----END CERTIFICATE-----
          title: publicKey
          type: string
        verifyClientMode:
          default: "off"
          enum:
          - "off"
          - "on"
          - optional
          title: verifyClientMode
          type: string
        clientCertLabel:
          title: clientCertLabel
          type: string
        clientCert:
          example: |-
            -----BEGIN CERTIFICATE----
            MIIF3TCCA8WgAwIBAgIUBFyq+
            -----END CERTIFICATE-----
          title: clientCert
          type: string
        revocationListLabel:
          title: revocationListLabel
          type: string
        revocationList:
          example: |
            -----BEGIN X509 CRL-----
            MIIDDzCB+AIBATANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQ
            -----END X509 CRL-----
          title: revocationList
          type: string
        mappings:
          items:
            $ref: '#/components/schemas/dlbPostBody_sslEndpoints_inner_mappings_inner'
          type: array
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
