/*
Identity Provider Management API

Description of Identity Provider API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// checks if the SamlProviderPostBodyServiceProviderUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SamlProviderPostBodyServiceProviderUrls{}

// SamlProviderPostBodyServiceProviderUrls struct for SamlProviderPostBodyServiceProviderUrls
type SamlProviderPostBodyServiceProviderUrls struct {
	SignOn string `json:"sign_on"`
	SignOut string `json:"sign_out"`
}

// NewSamlProviderPostBodyServiceProviderUrls instantiates a new SamlProviderPostBodyServiceProviderUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSamlProviderPostBodyServiceProviderUrls(signOn string, signOut string) *SamlProviderPostBodyServiceProviderUrls {
	this := SamlProviderPostBodyServiceProviderUrls{}
	this.SignOn = signOn
	this.SignOut = signOut
	return &this
}

// NewSamlProviderPostBodyServiceProviderUrlsWithDefaults instantiates a new SamlProviderPostBodyServiceProviderUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSamlProviderPostBodyServiceProviderUrlsWithDefaults() *SamlProviderPostBodyServiceProviderUrls {
	this := SamlProviderPostBodyServiceProviderUrls{}
	return &this
}

// GetSignOn returns the SignOn field value
func (o *SamlProviderPostBodyServiceProviderUrls) GetSignOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignOn
}

// GetSignOnOk returns a tuple with the SignOn field value
// and a boolean to check if the value has been set.
func (o *SamlProviderPostBodyServiceProviderUrls) GetSignOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignOn, true
}

// SetSignOn sets field value
func (o *SamlProviderPostBodyServiceProviderUrls) SetSignOn(v string) {
	o.SignOn = v
}

// GetSignOut returns the SignOut field value
func (o *SamlProviderPostBodyServiceProviderUrls) GetSignOut() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignOut
}

// GetSignOutOk returns a tuple with the SignOut field value
// and a boolean to check if the value has been set.
func (o *SamlProviderPostBodyServiceProviderUrls) GetSignOutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignOut, true
}

// SetSignOut sets field value
func (o *SamlProviderPostBodyServiceProviderUrls) SetSignOut(v string) {
	o.SignOut = v
}

func (o SamlProviderPostBodyServiceProviderUrls) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SamlProviderPostBodyServiceProviderUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sign_on"] = o.SignOn
	toSerialize["sign_out"] = o.SignOut
	return toSerialize, nil
}

type NullableSamlProviderPostBodyServiceProviderUrls struct {
	value *SamlProviderPostBodyServiceProviderUrls
	isSet bool
}

func (v NullableSamlProviderPostBodyServiceProviderUrls) Get() *SamlProviderPostBodyServiceProviderUrls {
	return v.value
}

func (v *NullableSamlProviderPostBodyServiceProviderUrls) Set(val *SamlProviderPostBodyServiceProviderUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableSamlProviderPostBodyServiceProviderUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableSamlProviderPostBodyServiceProviderUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSamlProviderPostBodyServiceProviderUrls(val *SamlProviderPostBodyServiceProviderUrls) *NullableSamlProviderPostBodyServiceProviderUrls {
	return &NullableSamlProviderPostBodyServiceProviderUrls{value: val, isSet: true}
}

func (v NullableSamlProviderPostBodyServiceProviderUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSamlProviderPostBodyServiceProviderUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


