/*
Identity Provider Management API

Description of Identity Provider API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// checks if the OpenIDProviderDynamicPostBodyOidcProviderClientRegistration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIDProviderDynamicPostBodyOidcProviderClientRegistration{}

// OpenIDProviderDynamicPostBodyOidcProviderClientRegistration struct for OpenIDProviderDynamicPostBodyOidcProviderClientRegistration
type OpenIDProviderDynamicPostBodyOidcProviderClientRegistration struct {
	Authorization string `json:"authorization"`
}

// NewOpenIDProviderDynamicPostBodyOidcProviderClientRegistration instantiates a new OpenIDProviderDynamicPostBodyOidcProviderClientRegistration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDProviderDynamicPostBodyOidcProviderClientRegistration(authorization string) *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration {
	this := OpenIDProviderDynamicPostBodyOidcProviderClientRegistration{}
	this.Authorization = authorization
	return &this
}

// NewOpenIDProviderDynamicPostBodyOidcProviderClientRegistrationWithDefaults instantiates a new OpenIDProviderDynamicPostBodyOidcProviderClientRegistration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDProviderDynamicPostBodyOidcProviderClientRegistrationWithDefaults() *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration {
	this := OpenIDProviderDynamicPostBodyOidcProviderClientRegistration{}
	return &this
}

// GetAuthorization returns the Authorization field value
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) GetAuthorization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) GetAuthorizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorization, true
}

// SetAuthorization sets field value
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) SetAuthorization(v string) {
	o.Authorization = v
}

func (o OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorization"] = o.Authorization
	return toSerialize, nil
}

type NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration struct {
	value *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration
	isSet bool
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) Get() *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration {
	return v.value
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) Set(val *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration(val *OpenIDProviderDynamicPostBodyOidcProviderClientRegistration) *NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration {
	return &NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration{value: val, isSet: true}
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientRegistration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


