/*
Identity Provider Management API

Description of Identity Provider API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// checks if the OpenIDProviderManualPostBodyOidcProviderUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIDProviderManualPostBodyOidcProviderUrls{}

// OpenIDProviderManualPostBodyOidcProviderUrls struct for OpenIDProviderManualPostBodyOidcProviderUrls
type OpenIDProviderManualPostBodyOidcProviderUrls struct {
	Authorize string `json:"authorize"`
	Token string `json:"token"`
	Userinfo string `json:"userinfo"`
}

// NewOpenIDProviderManualPostBodyOidcProviderUrls instantiates a new OpenIDProviderManualPostBodyOidcProviderUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDProviderManualPostBodyOidcProviderUrls(authorize string, token string, userinfo string) *OpenIDProviderManualPostBodyOidcProviderUrls {
	this := OpenIDProviderManualPostBodyOidcProviderUrls{}
	this.Authorize = authorize
	this.Token = token
	this.Userinfo = userinfo
	return &this
}

// NewOpenIDProviderManualPostBodyOidcProviderUrlsWithDefaults instantiates a new OpenIDProviderManualPostBodyOidcProviderUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDProviderManualPostBodyOidcProviderUrlsWithDefaults() *OpenIDProviderManualPostBodyOidcProviderUrls {
	this := OpenIDProviderManualPostBodyOidcProviderUrls{}
	return &this
}

// GetAuthorize returns the Authorize field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetAuthorize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authorize
}

// GetAuthorizeOk returns a tuple with the Authorize field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetAuthorizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorize, true
}

// SetAuthorize sets field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) SetAuthorize(v string) {
	o.Authorize = v
}

// GetToken returns the Token field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) SetToken(v string) {
	o.Token = v
}

// GetUserinfo returns the Userinfo field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetUserinfo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userinfo
}

// GetUserinfoOk returns a tuple with the Userinfo field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) GetUserinfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userinfo, true
}

// SetUserinfo sets field value
func (o *OpenIDProviderManualPostBodyOidcProviderUrls) SetUserinfo(v string) {
	o.Userinfo = v
}

func (o OpenIDProviderManualPostBodyOidcProviderUrls) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIDProviderManualPostBodyOidcProviderUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorize"] = o.Authorize
	toSerialize["token"] = o.Token
	toSerialize["userinfo"] = o.Userinfo
	return toSerialize, nil
}

type NullableOpenIDProviderManualPostBodyOidcProviderUrls struct {
	value *OpenIDProviderManualPostBodyOidcProviderUrls
	isSet bool
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderUrls) Get() *OpenIDProviderManualPostBodyOidcProviderUrls {
	return v.value
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderUrls) Set(val *OpenIDProviderManualPostBodyOidcProviderUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDProviderManualPostBodyOidcProviderUrls(val *OpenIDProviderManualPostBodyOidcProviderUrls) *NullableOpenIDProviderManualPostBodyOidcProviderUrls {
	return &NullableOpenIDProviderManualPostBodyOidcProviderUrls{value: val, isSet: true}
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


