/*
Identity Provider Management API

Description of Identity Provider API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// checks if the OpenIDProviderManualPostBodyOidcProviderClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIDProviderManualPostBodyOidcProviderClient{}

// OpenIDProviderManualPostBodyOidcProviderClient struct for OpenIDProviderManualPostBodyOidcProviderClient
type OpenIDProviderManualPostBodyOidcProviderClient struct {
	Credentials OpenIDProviderManualPostBodyOidcProviderClientCredentials `json:"credentials"`
}

// NewOpenIDProviderManualPostBodyOidcProviderClient instantiates a new OpenIDProviderManualPostBodyOidcProviderClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDProviderManualPostBodyOidcProviderClient(credentials OpenIDProviderManualPostBodyOidcProviderClientCredentials) *OpenIDProviderManualPostBodyOidcProviderClient {
	this := OpenIDProviderManualPostBodyOidcProviderClient{}
	this.Credentials = credentials
	return &this
}

// NewOpenIDProviderManualPostBodyOidcProviderClientWithDefaults instantiates a new OpenIDProviderManualPostBodyOidcProviderClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDProviderManualPostBodyOidcProviderClientWithDefaults() *OpenIDProviderManualPostBodyOidcProviderClient {
	this := OpenIDProviderManualPostBodyOidcProviderClient{}
	return &this
}

// GetCredentials returns the Credentials field value
func (o *OpenIDProviderManualPostBodyOidcProviderClient) GetCredentials() OpenIDProviderManualPostBodyOidcProviderClientCredentials {
	if o == nil {
		var ret OpenIDProviderManualPostBodyOidcProviderClientCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderManualPostBodyOidcProviderClient) GetCredentialsOk() (*OpenIDProviderManualPostBodyOidcProviderClientCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *OpenIDProviderManualPostBodyOidcProviderClient) SetCredentials(v OpenIDProviderManualPostBodyOidcProviderClientCredentials) {
	o.Credentials = v
}

func (o OpenIDProviderManualPostBodyOidcProviderClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIDProviderManualPostBodyOidcProviderClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credentials"] = o.Credentials
	return toSerialize, nil
}

type NullableOpenIDProviderManualPostBodyOidcProviderClient struct {
	value *OpenIDProviderManualPostBodyOidcProviderClient
	isSet bool
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderClient) Get() *OpenIDProviderManualPostBodyOidcProviderClient {
	return v.value
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderClient) Set(val *OpenIDProviderManualPostBodyOidcProviderClient) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderClient) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDProviderManualPostBodyOidcProviderClient(val *OpenIDProviderManualPostBodyOidcProviderClient) *NullableOpenIDProviderManualPostBodyOidcProviderClient {
	return &NullableOpenIDProviderManualPostBodyOidcProviderClient{value: val, isSet: true}
}

func (v NullableOpenIDProviderManualPostBodyOidcProviderClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDProviderManualPostBodyOidcProviderClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


