/*
Identity Provider Management API

Description of Identity Provider API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// checks if the OpenIDProviderDynamicPostBodyOidcProviderClientUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIDProviderDynamicPostBodyOidcProviderClientUrls{}

// OpenIDProviderDynamicPostBodyOidcProviderClientUrls struct for OpenIDProviderDynamicPostBodyOidcProviderClientUrls
type OpenIDProviderDynamicPostBodyOidcProviderClientUrls struct {
	Register string `json:"register"`
}

// NewOpenIDProviderDynamicPostBodyOidcProviderClientUrls instantiates a new OpenIDProviderDynamicPostBodyOidcProviderClientUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDProviderDynamicPostBodyOidcProviderClientUrls(register string) *OpenIDProviderDynamicPostBodyOidcProviderClientUrls {
	this := OpenIDProviderDynamicPostBodyOidcProviderClientUrls{}
	this.Register = register
	return &this
}

// NewOpenIDProviderDynamicPostBodyOidcProviderClientUrlsWithDefaults instantiates a new OpenIDProviderDynamicPostBodyOidcProviderClientUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDProviderDynamicPostBodyOidcProviderClientUrlsWithDefaults() *OpenIDProviderDynamicPostBodyOidcProviderClientUrls {
	this := OpenIDProviderDynamicPostBodyOidcProviderClientUrls{}
	return &this
}

// GetRegister returns the Register field value
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientUrls) GetRegister() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Register
}

// GetRegisterOk returns a tuple with the Register field value
// and a boolean to check if the value has been set.
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientUrls) GetRegisterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Register, true
}

// SetRegister sets field value
func (o *OpenIDProviderDynamicPostBodyOidcProviderClientUrls) SetRegister(v string) {
	o.Register = v
}

func (o OpenIDProviderDynamicPostBodyOidcProviderClientUrls) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIDProviderDynamicPostBodyOidcProviderClientUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["register"] = o.Register
	return toSerialize, nil
}

type NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls struct {
	value *OpenIDProviderDynamicPostBodyOidcProviderClientUrls
	isSet bool
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) Get() *OpenIDProviderDynamicPostBodyOidcProviderClientUrls {
	return v.value
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) Set(val *OpenIDProviderDynamicPostBodyOidcProviderClientUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls(val *OpenIDProviderDynamicPostBodyOidcProviderClientUrls) *NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls {
	return &NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls{value: val, isSet: true}
}

func (v NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDProviderDynamicPostBodyOidcProviderClientUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


